import type { Experience } from '@/types';

export const INITIAL_EXPERIENCES: Experience[] = [
  {
    id: '7',
    name: 'Gender Reveal Martinez Gonzalez Family',
    slug: 'gender-reveal-martinez-gonzalez-family',
    url: 'https://anayap.tech/reveal/',
    description: 'A private family gender reveal celebration page with event details and guest information.',
    category: 'Gender Reveal',
    status: 'active',
    thumbnail: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://events.anayap.tech/remoteEntry.js',
    createdBy: 'anayap04',
    createdAt: '2026-09-17',
    lastModified: '2026-09-17',
  },
  {
    id: '1',
    name: 'Rivera Family Baby Shower',
    slug: 'rivera-baby-shower',
    url: 'https://babyshower.riveras.family',
    description: 'A private celebration page for our baby shower — RSVP, gift registry, venue details, and photo album for guests.',
    category: 'Baby Shower',
    status: 'active',
    thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://events.anayap.tech/remoteEntry.js',
    createdBy: 'anayap04',
    createdAt: '2026-07-15',
    lastModified: '2026-09-10',
  },
  {
    id: '2',
    name: 'Q3 Product Leadership Offsite',
    slug: 'product-leadership-offsite',
    url: 'https://offsite.internal.acme.co',
    description: 'Private agenda, session notes, speaker bios, and hotel info for the 3-day leadership conference in Sonoma.',
    category: 'Conference',
    status: 'active',
    thumbnail: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://events.anayap.tech/remoteEntry.js',
    createdBy: 'anayap04',
    createdAt: '2026-06-01',
    lastModified: '2026-09-05',
  },
  {
    id: '3',
    name: "Sophie's 30th Birthday",
    slug: 'sophie-30th-birthday',
    url: 'https://sophie30.party',
    description: 'Surprise birthday celebration for Sophie — venue surprise reveal on the day, RSVP tracking, and a shared memory wall.',
    category: 'Birthday',
    status: 'draft',
    thumbnail: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://experiences.anayap.tech/remoteEntry.js',
    createdBy: 'alexrivera',
    createdAt: '2026-08-20',
    lastModified: '2026-09-12',
  },
  {
    id: '4',
    name: 'Chen & Nakamura Wedding',
    slug: 'chen-nakamura-wedding',
    url: 'https://chennakamura.wedding',
    description: 'Wedding info hub with ceremony details, accommodation options, dietary preferences form, and a live photo stream for guests.',
    category: 'Wedding',
    status: 'active',
    thumbnail: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://experiences.anayap.tech/remoteEntry.js',
    createdBy: 'anayap04',
    createdAt: '2026-03-10',
    lastModified: '2026-08-28',
  },
  {
    id: '5',
    name: 'Morales Family Reunion 2026',
    slug: 'morales-reunion-2026',
    url: 'https://moralesreunion.com',
    description: 'Annual family gathering page with potluck signup, activity schedule, directions to the lake house, and a photo booth uploader.',
    category: 'Family Reunion',
    status: 'active',
    thumbnail: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://events.anayap.tech/remoteEntry.js',
    createdBy: 'alexrivera',
    createdAt: '2026-04-22',
    lastModified: '2026-09-01',
  },
  {
    id: '6',
    name: 'Design Dept Farewell — Mia',
    slug: 'design-farewell-mia',
    url: 'https://farewell.mia.internal',
    description: 'Team farewell for Mia Santos — a private tribute page where colleagues can leave messages, share memories, and view the event schedule.',
    category: 'Farewell',
    status: 'archived',
    thumbnail: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&h=340&fit=crop&auto=format',
    mfeRemoteUrl: 'https://tickets.anayap.tech/remoteEntry.js',
    createdBy: 'anayap04',
    createdAt: '2025-11-05',
    lastModified: '2025-12-14',
  },
];
