sonar.organization=anayap04
sonar.projectKey=anayap04_events-experiences-host
sonar.projectName=events-experiences-host
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=node_modules/**,.next/**,dist/**,coverage/**,database/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
